name: Continuous Deployment

on:
  push:
    branches:
      - feat/github-actions-deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      